-- Bootstrap for MUSIC_PREFS. Idempotent: safe to re-run.

CREATE DATABASE IF NOT EXISTS MUSIC_PREFS;

CREATE WAREHOUSE IF NOT EXISTS WH_TRANSFORM
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

-- Monitoring runs on its own warehouse so that Soda and Monte Carlo never
-- compete with the build, and their cost can be attributed separately.
CREATE WAREHOUSE IF NOT EXISTS WH_MONITOR
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

CREATE ROLE IF NOT EXISTS TRANSFORMER;
CREATE ROLE IF NOT EXISTS MONITOR_RO;

GRANT USAGE ON WAREHOUSE WH_TRANSFORM TO ROLE TRANSFORMER;
GRANT USAGE ON WAREHOUSE WH_MONITOR   TO ROLE MONITOR_RO;
GRANT USAGE ON DATABASE MUSIC_PREFS   TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE MUSIC_PREFS   TO ROLE MONITOR_RO;
GRANT CREATE SCHEMA ON DATABASE MUSIC_PREFS TO ROLE TRANSFORMER;

CREATE SCHEMA IF NOT EXISTS MUSIC_PREFS.RAW;
CREATE SCHEMA IF NOT EXISTS MUSIC_PREFS.STAGING;
CREATE SCHEMA IF NOT EXISTS MUSIC_PREFS.CORE;
CREATE SCHEMA IF NOT EXISTS MUSIC_PREFS.MARTS;

GRANT USAGE ON ALL SCHEMAS IN DATABASE MUSIC_PREFS TO ROLE TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON ALL SCHEMAS IN DATABASE MUSIC_PREFS TO ROLE TRANSFORMER;

-- Monte Carlo and Soda read everything and write nothing.
GRANT USAGE  ON ALL SCHEMAS IN DATABASE MUSIC_PREFS TO ROLE MONITOR_RO;
GRANT SELECT ON ALL TABLES  IN DATABASE MUSIC_PREFS TO ROLE MONITOR_RO;
GRANT SELECT ON FUTURE TABLES IN DATABASE MUSIC_PREFS TO ROLE MONITOR_RO;
GRANT SELECT ON FUTURE VIEWS  IN DATABASE MUSIC_PREFS TO ROLE MONITOR_RO;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE MONITOR_RO;

CREATE TABLE IF NOT EXISTS MUSIC_PREFS.RAW.LISTENING_EVENTS (
  EVENT_ID      STRING,
  USER_ID       STRING,
  SESSION_ID    STRING,
  SONG_ID       STRING,
  ARTIST_ID     STRING,
  GENRE         STRING,
  EVENT_TYPE    STRING,
  EVENT_TS      TIMESTAMP_NTZ,
  DURATION_MS   NUMBER,
  MS_PLAYED     NUMBER,
  DEVICE_TYPE   STRING,
  COUNTRY       STRING,
  _INGESTED_AT  TIMESTAMP_NTZ,
  _SOURCE_FILE  STRING,
  _BATCH_ID     STRING,
  _LOADED_AT    TIMESTAMP_NTZ
);

-- Rows the contract rejected, kept with their reason so the rejection is
-- auditable rather than a number in a log that scrolled away.
CREATE TABLE IF NOT EXISTS MUSIC_PREFS.RAW.LISTENING_EVENTS_QUARANTINE (
  EVENT_ID           STRING,
  USER_ID            STRING,
  SESSION_ID         STRING,
  SONG_ID            STRING,
  ARTIST_ID          STRING,
  GENRE              STRING,
  EVENT_TYPE         STRING,
  EVENT_TS           TIMESTAMP_NTZ,
  DURATION_MS        STRING,
  MS_PLAYED          STRING,
  DEVICE_TYPE        STRING,
  COUNTRY            STRING,
  _INGESTED_AT       TIMESTAMP_NTZ,
  _SOURCE_FILE       STRING,
  _QUARANTINE_REASON STRING,
  _QUARANTINED_AT    TIMESTAMP_NTZ,
  _BATCH_ID          STRING,
  _LOADED_AT         TIMESTAMP_NTZ
);

-- Contract results inside the warehouse, so detection latency is a SQL query
-- and not something reconstructed by hand from console output.
CREATE TABLE IF NOT EXISTS MUSIC_PREFS.RAW.GE_VALIDATION_RESULTS (
  BATCH_ID            STRING,
  CONTRACT_VERSION    STRING,
  VALIDATED_AT        STRING,
  VERDICT             STRING,
  ROWS_IN             NUMBER,
  ROWS_CLEAN          NUMBER,
  ROWS_QUARANTINED    NUMBER,
  FAILED_EXPECTATIONS STRING,
  CHECKS_JSON         STRING
);

CREATE TABLE IF NOT EXISTS MUSIC_PREFS.RAW.SONGS (
  SONG_ID     STRING,
  SONG_NAME   STRING,
  ARTIST_ID   STRING,
  GENRE       STRING,
  DURATION_MS NUMBER
);

CREATE TABLE IF NOT EXISTS MUSIC_PREFS.RAW.ARTISTS (
  ARTIST_ID   STRING,
  ARTIST_NAME STRING,
  GENRE       STRING
);

-- Dataset-level certification, written by the pipeline after Soda has run.
-- This is the flag a consumer trusts, and it is decided by the quality gates
-- rather than computed alongside the data it is meant to judge.
CREATE TABLE IF NOT EXISTS MUSIC_PREFS.MARTS.DATA_QUALITY_STATUS (
  DATASET           STRING,
  BATCH_ID          STRING,
  EVALUATED_AT      TIMESTAMP_NTZ,
  CERTIFIED         BOOLEAN,
  CHECKS_EVALUATED  NUMBER,
  CHECKS_PASSED     NUMBER,
  CHECKS_WARNED     NUMBER,
  CHECKS_FAILED     NUMBER,
  FAILED_CHECK_NAMES STRING
);

-- Detection evidence for the anomaly experiment.
CREATE TABLE IF NOT EXISTS MUSIC_PREFS.MARTS.DETECTION_EVENTS (
  RUN_ID        STRING,
  ANOMALY       STRING,
  CONTROL       STRING,
  DETECTED      BOOLEAN,
  DETAIL        STRING,
  INJECTED_AT   TIMESTAMP_NTZ,
  DETECTED_AT   TIMESTAMP_NTZ,
  LATENCY_SECONDS NUMBER
);
